ktor:
    application:
        modules:
            - dam.nathan.ApplicationKt.module
    deployment:
        port: 8090
        #TODO Change port back to 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
